n = input()

count = {}
count["A"] = (n.count('a') + n.count('A'))
count["B"] = (n.count('b') + n.count('B'))
count["C"] = (n.count('c') + n.count('C'))
count["D"] = (n.count('d') + n.count('D'))
count["E"] = (n.count('e') + n.count('E'))
count["F"] = (n.count('f') + n.count('F'))
count["G"] = (n.count('g') + n.count('G'))
count["H"] = (n.count('h') + n.count('H'))
count["I"] = (n.count('i') + n.count('I'))
count["J"] = (n.count('j') + n.count('J'))
count["K"] = (n.count('k') + n.count('K'))
count["L"] = (n.count('l') + n.count('L'))
count["M"] = (n.count('m') + n.count('M'))
count["N"] = (n.count('n') + n.count('N'))
count["O"] = (n.count('o') + n.count('O'))
count["P"] = (n.count('p') + n.count('P'))
count["Q"] = (n.count('q') + n.count('Q'))
count["R"] = (n.count('r') + n.count('R'))
count["S"] = (n.count('s') + n.count('S'))
count["T"] = (n.count('t') + n.count('T'))
count["U"] = (n.count('u') + n.count('U'))
count["V"] = (n.count('v') + n.count('V'))
count["W"] = (n.count('w') + n.count('W'))
count["X"] = (n.count('x') + n.count('X'))
count["Y"] = (n.count('y') + n.count('Y'))
count["Z"] = (n.count('z') + n.count('Z'))

print(count)